[2025-07-01T22:10:01.336+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-01T22:10:01.435+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:08:00+00:00 [queued]>
[2025-07-01T22:10:01.453+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:08:00+00:00 [queued]>
[2025-07-01T22:10:01.455+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-01T22:10:01.484+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): dbt_run_silver> on 2025-07-01 22:08:00+00:00
[2025-07-01T22:10:01.497+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=742) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-01T22:10:01.499+0000] {standard_task_runner.py:64} INFO - Started process 743 to run task
[2025-07-01T22:10:01.500+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_trino_silver_pipeline', 'dbt_run_silver', 'scheduled__2025-07-01T22:08:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dbt_trino_silver_dag.py', '--cfg-path', '/tmp/tmpj1uzmqlg']
[2025-07-01T22:10:01.502+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask dbt_run_silver
[2025-07-01T22:10:01.618+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:08:00+00:00 [running]> on host 891f6be6864d
[2025-07-01T22:10:01.762+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@example.com' AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='dbt_trino_silver_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T22:08:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T22:08:00+00:00'
[2025-07-01T22:10:01.763+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-01T22:10:01.815+0000] {docker.py:367} INFO - Starting docker container from image modern-data-pipeline-dbt-trino:latest
[2025-07-01T22:10:02.285+0000] {docker.py:438} INFO - === Executando dbt run incremental ===
[2025-07-01T22:10:06.103+0000] {docker.py:438} INFO - [0m22:10:06  Running with dbt=1.7.0
[2025-07-01T22:10:06.624+0000] {docker.py:438} INFO - [0m22:10:06  Registered adapter: trino=1.7.0
[2025-07-01T22:10:06.718+0000] {docker.py:438} INFO - [0m22:10:06  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-07-01T22:10:06.718+0000] {docker.py:438} INFO - There are 1 unused configuration paths:
[2025-07-01T22:10:06.719+0000] {docker.py:438} INFO - - models.agronegocio_iceberg.staging
[2025-07-01T22:10:06.748+0000] {docker.py:438} INFO - [0m22:10:06  Found 1 model, 29 tests, 2 operations, 1 source, 0 exposures, 0 metrics, 541 macros, 0 groups, 0 semantic models
[2025-07-01T22:10:06.751+0000] {docker.py:438} INFO - [0m22:10:06
[2025-07-01T22:10:07.140+0000] {docker.py:438} INFO - [0m22:10:07
[2025-07-01T22:10:07.142+0000] {docker.py:438} INFO - [0m22:10:07  Running 1 on-run-start hook
[2025-07-01T22:10:07.149+0000] {docker.py:438} INFO - [0m22:10:07  Iniciando execu√ß√£o do dbt com Trino/Iceberg
[2025-07-01T22:10:07.158+0000] {docker.py:438} INFO - [0m22:10:07  1 of 1 START hook: agronegocio_iceberg.on-run-start.0 .......................... [RUN]
[2025-07-01T22:10:07.160+0000] {docker.py:438} INFO - [0m22:10:07  1 of 1 OK hook: agronegocio_iceberg.on-run-start.0 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T22:10:07.161+0000] {docker.py:438} INFO - [0m22:10:07
[2025-07-01T22:10:07.163+0000] {docker.py:438} INFO - [0m22:10:07  Concurrency: 2 threads (target='dev')
[2025-07-01T22:10:07.164+0000] {docker.py:438} INFO - [0m22:10:07
[2025-07-01T22:10:07.178+0000] {docker.py:438} INFO - [0m22:10:07  1 of 1 START sql incremental model silver_silver.silver_dados_produtores_agro_trino  [RUN]
[2025-07-01T22:10:07.358+0000] {docker.py:438} INFO - [0m22:10:07  Schema silver criado/verificado
[2025-07-01T22:10:07.488+0000] {docker.py:438} INFO - [0m22:10:07  1 of 1 ERROR creating sql incremental model silver_silver.silver_dados_produtores_agro_trino  [[31mERROR[0m in 0.31s]
[2025-07-01T22:10:07.494+0000] {docker.py:438} INFO - [0m22:10:07
[2025-07-01T22:10:07.494+0000] {docker.py:438} INFO - [0m22:10:07  Running 1 on-run-end hook
[2025-07-01T22:10:07.500+0000] {docker.py:438} INFO - [0m22:10:07  Execu√ß√£o finalizada
[2025-07-01T22:10:07.501+0000] {docker.py:438} INFO - [0m22:10:07  1 of 1 START hook: agronegocio_iceberg.on-run-end.0 ............................ [RUN]
[2025-07-01T22:10:07.502+0000] {docker.py:438} INFO - [0m22:10:07  1 of 1 OK hook: agronegocio_iceberg.on-run-end.0 ............................... [[32mOK[0m in 0.00s]
[2025-07-01T22:10:07.503+0000] {docker.py:438} INFO - [0m22:10:07
[2025-07-01T22:10:07.506+0000] {docker.py:438} INFO - [0m22:10:07
[2025-07-01T22:10:07.507+0000] {docker.py:438} INFO - [0m22:10:07  Finished running 1 incremental model, 2 hooks in 0 hours 0 minutes and 0.75 seconds (0.75s).
[2025-07-01T22:10:07.523+0000] {docker.py:438} INFO - [0m22:10:07
[2025-07-01T22:10:07.524+0000] {docker.py:438} INFO - [0m22:10:07  [31mCompleted with 1 error and 0 warnings:[0m
[2025-07-01T22:10:07.524+0000] {docker.py:438} INFO - [0m22:10:07
[2025-07-01T22:10:07.525+0000] {docker.py:438} INFO - [0m22:10:07    Database Error in model silver_dados_produtores_agro_trino (models/silver/silver_dados_produtores_agro_trino.sql)
[2025-07-01T22:10:07.526+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 104:18: Column 'serasa_score' cannot be resolved", query_id=20250701_221007_00039_tzkb6)
[2025-07-01T22:10:07.526+0000] {docker.py:438} INFO -   compiled Code at target/run/agronegocio_iceberg/models/silver/silver_dados_produtores_agro_trino.sql
[2025-07-01T22:10:07.526+0000] {docker.py:438} INFO - [0m22:10:07
[2025-07-01T22:10:07.527+0000] {docker.py:438} INFO - [0m22:10:07  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-07-01T22:10:08.673+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-01T22:10:08.684+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-01T22:10:08.690+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_trino_silver_pipeline, task_id=dbt_run_silver, run_id=scheduled__2025-07-01T22:08:00+00:00, execution_date=20250701T220800, start_date=20250701T221001, end_date=20250701T221008
[2025-07-01T22:10:08.704+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 18 for task dbt_run_silver (Docker container failed: {'StatusCode': 1}; 743)
[2025-07-01T22:10:08.725+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-01T22:10:08.753+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T22:10:08.759+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
