[2025-07-01T22:12:02.101+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-01T22:12:02.151+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:10:00+00:00 [queued]>
[2025-07-01T22:12:02.168+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:10:00+00:00 [queued]>
[2025-07-01T22:12:02.169+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-01T22:12:02.196+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): dbt_run_silver> on 2025-07-01 22:10:00+00:00
[2025-07-01T22:12:02.206+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=774) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-01T22:12:02.207+0000] {standard_task_runner.py:64} INFO - Started process 775 to run task
[2025-07-01T22:12:02.210+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_trino_silver_pipeline', 'dbt_run_silver', 'scheduled__2025-07-01T22:10:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dbt_trino_silver_dag.py', '--cfg-path', '/tmp/tmpc6aax0w3']
[2025-07-01T22:12:02.213+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask dbt_run_silver
[2025-07-01T22:12:02.287+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:10:00+00:00 [running]> on host 891f6be6864d
[2025-07-01T22:12:02.450+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@example.com' AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='dbt_trino_silver_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T22:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T22:10:00+00:00'
[2025-07-01T22:12:02.453+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-01T22:12:02.523+0000] {docker.py:367} INFO - Starting docker container from image modern-data-pipeline-dbt-trino:latest
[2025-07-01T22:12:02.887+0000] {docker.py:438} INFO - === Executando dbt run incremental ===
[2025-07-01T22:12:06.518+0000] {docker.py:438} INFO - [0m22:12:06  Running with dbt=1.7.0
[2025-07-01T22:12:07.042+0000] {docker.py:438} INFO - [0m22:12:07  Registered adapter: trino=1.7.0
[2025-07-01T22:12:07.135+0000] {docker.py:438} INFO - [0m22:12:07  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-07-01T22:12:07.136+0000] {docker.py:438} INFO - There are 1 unused configuration paths:
[2025-07-01T22:12:07.136+0000] {docker.py:438} INFO - - models.agronegocio_iceberg.staging
[2025-07-01T22:12:07.172+0000] {docker.py:438} INFO - [0m22:12:07  Found 1 model, 29 tests, 2 operations, 1 source, 0 exposures, 0 metrics, 541 macros, 0 groups, 0 semantic models
[2025-07-01T22:12:07.175+0000] {docker.py:438} INFO - [0m22:12:07
[2025-07-01T22:12:07.720+0000] {docker.py:438} INFO - [0m22:12:07
[2025-07-01T22:12:07.721+0000] {docker.py:438} INFO - [0m22:12:07  Running 1 on-run-start hook
[2025-07-01T22:12:07.726+0000] {docker.py:438} INFO - [0m22:12:07  Iniciando execu√ß√£o do dbt com Trino/Iceberg
[2025-07-01T22:12:07.733+0000] {docker.py:438} INFO - [0m22:12:07  1 of 1 START hook: agronegocio_iceberg.on-run-start.0 .......................... [RUN]
[2025-07-01T22:12:07.734+0000] {docker.py:438} INFO - [0m22:12:07  1 of 1 OK hook: agronegocio_iceberg.on-run-start.0 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T22:12:07.734+0000] {docker.py:438} INFO - [0m22:12:07
[2025-07-01T22:12:07.736+0000] {docker.py:438} INFO - [0m22:12:07  Concurrency: 2 threads (target='dev')
[2025-07-01T22:12:07.737+0000] {docker.py:438} INFO - [0m22:12:07
[2025-07-01T22:12:07.751+0000] {docker.py:438} INFO - [0m22:12:07  1 of 1 START sql incremental model silver_silver.silver_dados_produtores_agro_trino  [RUN]
[2025-07-01T22:12:07.939+0000] {docker.py:438} INFO - [0m22:12:07  Schema silver criado/verificado
[2025-07-01T22:12:08.056+0000] {docker.py:438} INFO - [0m22:12:08  1 of 1 ERROR creating sql incremental model silver_silver.silver_dados_produtores_agro_trino  [[31mERROR[0m in 0.30s]
[2025-07-01T22:12:08.060+0000] {docker.py:438} INFO - [0m22:12:08
[2025-07-01T22:12:08.061+0000] {docker.py:438} INFO - [0m22:12:08  Running 1 on-run-end hook
[2025-07-01T22:12:08.070+0000] {docker.py:438} INFO - [0m22:12:08  Execu√ß√£o finalizada
[2025-07-01T22:12:08.072+0000] {docker.py:438} INFO - [0m22:12:08  1 of 1 START hook: agronegocio_iceberg.on-run-end.0 ............................ [RUN]
[2025-07-01T22:12:08.073+0000] {docker.py:438} INFO - [0m22:12:08  1 of 1 OK hook: agronegocio_iceberg.on-run-end.0 ............................... [[32mOK[0m in 0.00s]
[2025-07-01T22:12:08.074+0000] {docker.py:438} INFO - [0m22:12:08
[2025-07-01T22:12:08.076+0000] {docker.py:438} INFO - [0m22:12:08
[2025-07-01T22:12:08.076+0000] {docker.py:438} INFO - [0m22:12:08  Finished running 1 incremental model, 2 hooks in 0 hours 0 minutes and 0.90 seconds (0.90s).
[2025-07-01T22:12:08.095+0000] {docker.py:438} INFO - [0m22:12:08
[2025-07-01T22:12:08.096+0000] {docker.py:438} INFO - [0m22:12:08  [31mCompleted with 1 error and 0 warnings:[0m
[2025-07-01T22:12:08.101+0000] {docker.py:438} INFO - [0m22:12:08  
[2025-07-01T22:12:08.102+0000] {docker.py:438} INFO - [0m22:12:08    Database Error in model silver_dados_produtores_agro_trino (models/silver/silver_dados_produtores_agro_trino.sql)
[2025-07-01T22:12:08.102+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 104:18: Column 'serasa_score' cannot be resolved", query_id=20250701_221207_00044_tzkb6)
[2025-07-01T22:12:08.102+0000] {docker.py:438} INFO -   compiled Code at target/run/agronegocio_iceberg/models/silver/silver_dados_produtores_agro_trino.sql
[2025-07-01T22:12:08.103+0000] {docker.py:438} INFO - [0m22:12:08  
[2025-07-01T22:12:08.103+0000] {docker.py:438} INFO - [0m22:12:08  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-07-01T22:12:09.284+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-01T22:12:09.291+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-01T22:12:09.295+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_trino_silver_pipeline, task_id=dbt_run_silver, run_id=scheduled__2025-07-01T22:10:00+00:00, execution_date=20250701T221000, start_date=20250701T221202, end_date=20250701T221209
[2025-07-01T22:12:09.306+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task dbt_run_silver (Docker container failed: {'StatusCode': 1}; 775)
[2025-07-01T22:12:09.318+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-01T22:12:09.340+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T22:12:09.344+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
