[2025-07-01T18:57:31.305+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T18:57:31.306+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T18:57:31.308+0000] {logging_mixin.py:188} INFO - [2025-07-01T18:57:31.307+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T18:57:31.318+0000] {logging_mixin.py:188} INFO - [2025-07-01T18:57:31.315+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T18:57:31.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T18:57:31.340+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.041 seconds
[2025-07-01T18:58:01.537+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T18:58:01.538+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T18:58:01.540+0000] {logging_mixin.py:188} INFO - [2025-07-01T18:58:01.540+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T18:58:01.552+0000] {logging_mixin.py:188} INFO - [2025-07-01T18:58:01.548+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T18:58:01.553+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T18:58:01.585+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.054 seconds
[2025-07-01T18:58:31.802+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T18:58:31.803+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T18:58:31.805+0000] {logging_mixin.py:188} INFO - [2025-07-01T18:58:31.804+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T18:58:31.813+0000] {logging_mixin.py:188} INFO - [2025-07-01T18:58:31.811+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T18:58:31.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T18:58:31.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.037 seconds
[2025-07-01T18:59:02.045+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T18:59:02.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T18:59:02.055+0000] {logging_mixin.py:188} INFO - [2025-07-01T18:59:02.055+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T18:59:02.078+0000] {logging_mixin.py:188} INFO - [2025-07-01T18:59:02.067+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T18:59:02.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T18:59:02.111+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.073 seconds
[2025-07-01T18:59:32.341+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T18:59:32.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T18:59:32.344+0000] {logging_mixin.py:188} INFO - [2025-07-01T18:59:32.344+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T18:59:32.356+0000] {logging_mixin.py:188} INFO - [2025-07-01T18:59:32.353+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T18:59:32.358+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T18:59:32.381+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.048 seconds
[2025-07-01T19:00:02.609+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:00:02.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:00:02.618+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:00:02.617+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:00:02.647+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:00:02.641+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:00:02.651+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:00:02.695+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.110 seconds
[2025-07-01T19:00:32.884+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:00:32.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:00:32.886+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:00:32.885+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:00:32.895+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:00:32.892+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:00:32.896+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:00:32.917+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.039 seconds
[2025-07-01T19:01:03.161+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:01:03.162+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:01:03.166+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:01:03.165+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:01:03.179+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:01:03.176+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:01:03.180+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:01:03.204+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.057 seconds
[2025-07-01T19:01:33.383+0000] {processor.py:161} INFO - Started process (PID=281) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:01:33.387+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:01:33.398+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:01:33.398+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:01:33.418+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:01:33.415+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:01:33.420+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:01:33.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.082 seconds
[2025-07-01T19:02:03.667+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:02:03.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:02:03.670+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:02:03.670+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:02:03.679+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:02:03.677+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:02:03.680+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:02:03.695+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.039 seconds
[2025-07-01T19:02:33.898+0000] {processor.py:161} INFO - Started process (PID=309) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:02:33.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:02:33.903+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:02:33.902+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:02:33.915+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:02:33.912+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:02:33.916+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:02:33.933+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.050 seconds
[2025-07-01T19:03:04.123+0000] {processor.py:161} INFO - Started process (PID=319) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:03:04.125+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:03:04.128+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:03:04.128+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:03:04.140+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:03:04.138+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:03:04.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:03:04.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.048 seconds
[2025-07-01T19:03:34.365+0000] {processor.py:161} INFO - Started process (PID=337) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:03:34.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:03:34.367+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:03:34.367+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:03:34.376+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:03:34.374+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:03:34.377+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:03:34.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.036 seconds
[2025-07-01T19:04:04.598+0000] {processor.py:161} INFO - Started process (PID=347) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:04:04.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:04:04.603+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:04:04.602+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:04:04.616+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:04:04.613+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:04:04.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:04:04.634+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.049 seconds
[2025-07-01T19:04:34.841+0000] {processor.py:161} INFO - Started process (PID=365) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:04:34.842+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:04:34.846+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:04:34.845+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:04:34.858+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:04:34.856+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:04:34.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:04:34.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.048 seconds
[2025-07-01T19:05:05.076+0000] {processor.py:161} INFO - Started process (PID=375) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:05:05.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:05:05.079+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:05:05.079+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:05:05.088+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:05:05.086+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:05:05.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:05:05.105+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.037 seconds
[2025-07-01T19:05:35.319+0000] {processor.py:161} INFO - Started process (PID=399) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:05:35.319+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:05:35.320+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:05:35.320+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:05:35.327+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:05:35.326+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:05:35.328+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:05:35.344+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.030 seconds
[2025-07-01T19:06:05.577+0000] {processor.py:161} INFO - Started process (PID=409) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:06:05.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:06:05.580+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:06:05.579+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:06:05.588+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:06:05.586+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:06:05.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:06:05.606+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.037 seconds
[2025-07-01T19:06:35.808+0000] {processor.py:161} INFO - Started process (PID=421) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:06:35.808+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:06:35.810+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:06:35.810+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:06:35.819+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:06:35.817+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:06:35.819+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:06:35.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.034 seconds
[2025-07-01T19:07:06.040+0000] {processor.py:161} INFO - Started process (PID=439) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:07:06.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:07:06.042+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:07:06.042+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:07:06.050+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:07:06.048+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:07:06.050+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:07:06.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.032 seconds
[2025-07-01T19:07:36.292+0000] {processor.py:161} INFO - Started process (PID=453) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:07:36.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:07:36.294+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:07:36.294+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:07:36.303+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:07:36.301+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:07:36.303+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:07:36.320+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.033 seconds
[2025-07-01T19:08:06.563+0000] {processor.py:161} INFO - Started process (PID=475) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:08:06.565+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:08:06.567+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:08:06.567+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:08:06.577+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:08:06.575+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:08:06.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:08:06.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.049 seconds
[2025-07-01T19:08:36.789+0000] {processor.py:161} INFO - Started process (PID=485) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:08:36.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:08:36.792+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:08:36.792+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:08:36.805+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:08:36.801+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:08:36.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:08:36.823+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.043 seconds
[2025-07-01T19:09:07.018+0000] {processor.py:161} INFO - Started process (PID=503) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:09:07.020+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:09:07.022+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:09:07.022+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:09:07.035+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:09:07.032+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:09:07.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:09:07.052+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.047 seconds
[2025-07-01T19:09:37.262+0000] {processor.py:161} INFO - Started process (PID=513) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:09:37.263+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:09:37.265+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:09:37.265+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:09:37.275+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:09:37.273+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:09:37.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:09:37.292+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.046 seconds
[2025-07-01T19:10:07.490+0000] {processor.py:161} INFO - Started process (PID=531) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:10:07.491+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:10:07.493+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:10:07.492+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:10:07.502+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:10:07.500+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:10:07.503+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:10:07.519+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.038 seconds
[2025-07-01T19:10:37.773+0000] {processor.py:161} INFO - Started process (PID=541) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:10:37.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:10:37.776+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:10:37.775+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:10:37.786+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:10:37.783+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:10:37.787+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:10:37.806+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.040 seconds
[2025-07-01T19:11:08.013+0000] {processor.py:161} INFO - Started process (PID=559) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:11:08.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:11:08.016+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:11:08.016+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:11:08.027+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:11:08.024+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:11:08.028+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:11:08.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.045 seconds
[2025-07-01T19:11:38.241+0000] {processor.py:161} INFO - Started process (PID=569) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:11:38.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:11:38.243+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:11:38.242+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:11:38.250+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:11:38.249+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:11:38.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:11:38.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.034 seconds
[2025-07-01T19:12:08.546+0000] {processor.py:161} INFO - Started process (PID=592) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:12:08.549+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:12:08.554+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:12:08.553+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:12:08.580+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:12:08.573+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:12:08.582+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:12:08.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.105 seconds
[2025-07-01T19:12:38.893+0000] {processor.py:161} INFO - Started process (PID=602) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:12:38.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:12:38.895+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:12:38.895+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:12:38.905+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:12:38.903+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:12:38.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:12:38.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.039 seconds
[2025-07-01T19:13:09.118+0000] {processor.py:161} INFO - Started process (PID=620) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:13:09.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:13:09.120+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:13:09.120+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:13:09.131+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:13:09.128+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:13:09.131+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:13:09.147+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.038 seconds
[2025-07-01T19:13:39.381+0000] {processor.py:161} INFO - Started process (PID=630) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:13:39.381+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:13:39.383+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:13:39.383+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:13:39.391+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:13:39.389+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:13:39.392+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:13:39.409+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.035 seconds
[2025-07-01T19:14:09.651+0000] {processor.py:161} INFO - Started process (PID=648) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:14:09.652+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:14:09.654+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:14:09.653+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:14:09.662+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:14:09.660+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:14:09.663+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:14:09.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.034 seconds
[2025-07-01T19:14:39.936+0000] {processor.py:161} INFO - Started process (PID=658) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:14:39.937+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:14:39.938+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:14:39.937+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:14:39.945+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:14:39.944+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:14:39.946+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:14:39.961+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.030 seconds
[2025-07-01T19:15:10.195+0000] {processor.py:161} INFO - Started process (PID=676) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:15:10.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:15:10.197+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:15:10.197+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:15:10.206+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:15:10.204+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:15:10.207+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:15:10.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.037 seconds
[2025-07-01T19:15:40.453+0000] {processor.py:161} INFO - Started process (PID=686) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:15:40.454+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:15:40.454+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:15:40.454+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:15:40.463+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:15:40.461+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:15:40.464+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:15:40.479+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.033 seconds
[2025-07-01T19:16:10.657+0000] {processor.py:161} INFO - Started process (PID=704) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:16:10.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:16:10.658+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:16:10.658+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:16:10.669+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:16:10.666+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:16:10.670+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:16:10.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.037 seconds
[2025-07-01T19:16:40.877+0000] {processor.py:161} INFO - Started process (PID=714) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:16:40.877+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:16:40.878+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:16:40.878+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:16:40.889+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:16:40.886+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:16:40.890+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:16:40.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.034 seconds
[2025-07-01T19:17:11.098+0000] {processor.py:161} INFO - Started process (PID=732) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:17:11.099+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:17:11.100+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:17:11.099+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:17:11.112+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:17:11.109+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:17:11.114+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:17:11.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.044 seconds
[2025-07-01T19:17:41.345+0000] {processor.py:161} INFO - Started process (PID=742) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:17:41.346+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:17:41.347+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:17:41.347+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:17:41.358+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:17:41.355+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:17:41.359+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:17:41.381+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.042 seconds
[2025-07-01T19:18:11.591+0000] {processor.py:161} INFO - Started process (PID=760) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:18:11.592+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:18:11.592+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:18:11.592+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:18:11.601+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:18:11.599+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:18:11.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:18:11.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.033 seconds
[2025-07-01T19:18:41.827+0000] {processor.py:161} INFO - Started process (PID=770) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:18:41.828+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:18:41.829+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:18:41.828+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:18:41.838+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:18:41.836+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:18:41.839+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:18:41.854+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.037 seconds
[2025-07-01T19:19:12.057+0000] {processor.py:161} INFO - Started process (PID=788) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:19:12.058+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:19:12.059+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:19:12.058+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:19:12.071+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:19:12.069+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:19:12.072+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:19:12.088+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.040 seconds
[2025-07-01T19:19:42.299+0000] {processor.py:161} INFO - Started process (PID=798) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:19:42.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:19:42.301+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:19:42.300+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:19:42.314+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:19:42.311+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:19:42.314+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:19:42.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.041 seconds
[2025-07-01T19:20:12.540+0000] {processor.py:161} INFO - Started process (PID=816) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:20:12.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:20:12.543+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:20:12.542+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:20:12.557+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:20:12.554+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:20:12.558+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:20:12.574+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.046 seconds
[2025-07-01T19:20:42.820+0000] {processor.py:161} INFO - Started process (PID=831) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:20:42.822+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:20:42.823+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:20:42.822+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:20:42.833+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:20:42.831+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:20:42.834+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:20:42.850+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.039 seconds
[2025-07-01T19:21:13.020+0000] {processor.py:161} INFO - Started process (PID=849) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:21:13.021+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:21:13.022+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:21:13.022+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:21:13.035+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:21:13.032+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:21:13.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:21:13.052+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.046 seconds
[2025-07-01T19:21:43.265+0000] {processor.py:161} INFO - Started process (PID=859) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:21:43.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:21:43.267+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:21:43.267+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:21:43.280+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:21:43.277+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:21:43.280+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:21:43.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.045 seconds
[2025-07-01T19:22:13.470+0000] {processor.py:161} INFO - Started process (PID=877) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:22:13.470+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:22:13.471+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:22:13.471+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:22:13.478+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:22:13.477+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:22:13.479+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:22:13.497+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.033 seconds
[2025-07-01T19:22:43.735+0000] {processor.py:161} INFO - Started process (PID=887) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:22:43.736+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:22:43.737+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:22:43.736+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:22:43.745+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:22:43.743+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:22:43.746+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:22:43.762+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.033 seconds
[2025-07-01T19:23:13.938+0000] {processor.py:161} INFO - Started process (PID=905) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:23:13.939+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:23:13.940+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:23:13.940+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:23:13.952+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:23:13.950+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:23:13.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:23:13.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.042 seconds
[2025-07-01T19:23:44.167+0000] {processor.py:161} INFO - Started process (PID=915) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:23:44.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:23:44.169+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:23:44.169+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:23:44.182+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:23:44.180+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:23:44.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:23:44.200+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.044 seconds
[2025-07-01T19:24:14.372+0000] {processor.py:161} INFO - Started process (PID=933) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:24:14.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:24:14.374+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:24:14.373+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:24:14.383+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:24:14.381+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:24:14.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:24:14.403+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.037 seconds
[2025-07-01T19:24:44.618+0000] {processor.py:161} INFO - Started process (PID=943) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:24:44.619+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:24:44.620+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:24:44.619+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:24:44.628+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:24:44.627+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:24:44.629+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:24:44.645+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.038 seconds
[2025-07-01T19:25:14.820+0000] {processor.py:161} INFO - Started process (PID=961) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:25:14.821+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:25:14.822+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:25:14.821+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:25:14.830+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:25:14.828+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:25:14.830+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:25:14.848+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.032 seconds
[2025-07-01T19:25:45.064+0000] {processor.py:161} INFO - Started process (PID=971) to work on /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:25:45.065+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dbt_silver_iceberg_dag.py for tasks to queue
[2025-07-01T19:25:45.066+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:25:45.066+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:25:45.078+0000] {logging_mixin.py:188} INFO - [2025-07-01T19:25:45.075+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dbt_silver_iceberg_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_silver_iceberg_dag.py", line 52, in <module>
    dbt_run_silver = DockerOperator(
                     ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 273, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: dbt_run_silver_models). Invalid arguments were:
**kwargs: {'volumes': ['/var/run/docker.sock:/var/run/docker.sock', '{{ dag_run.conf.get("dbt_project_path", "/opt/airflow/dbt") }}:/dbt']}
[2025-07-01T19:25:45.079+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_silver_iceberg_dag.py
[2025-07-01T19:25:45.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dbt_silver_iceberg_dag.py took 0.041 seconds
