[2025-07-01T22:42:16.442+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-01T22:42:16.559+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:40:00+00:00 [queued]>
[2025-07-01T22:42:16.590+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:40:00+00:00 [queued]>
[2025-07-01T22:42:16.591+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-01T22:42:16.633+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): dbt_run_silver> on 2025-07-01 22:40:00+00:00
[2025-07-01T22:42:16.653+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_trino_silver_pipeline', 'dbt_run_silver', 'scheduled__2025-07-01T22:40:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/dbt_trino_silver_dag.py', '--cfg-path', '/tmp/tmpt7g7ydin']
[2025-07-01T22:42:16.664+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask dbt_run_silver
[2025-07-01T22:42:16.671+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=185) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-01T22:42:16.676+0000] {standard_task_runner.py:64} INFO - Started process 186 to run task
[2025-07-01T22:42:16.830+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:40:00+00:00 [running]> on host 0a4aae371d36
[2025-07-01T22:42:17.113+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@example.com' AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='dbt_trino_silver_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T22:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T22:40:00+00:00'
[2025-07-01T22:42:17.114+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-01T22:42:17.267+0000] {docker.py:367} INFO - Starting docker container from image modern-data-pipeline-dbt-trino:latest
[2025-07-01T22:42:17.898+0000] {docker.py:438} INFO - === Executando dbt run incremental ===
[2025-07-01T22:42:25.919+0000] {docker.py:438} INFO - [0m22:42:25  Running with dbt=1.7.0
[2025-07-01T22:42:26.544+0000] {docker.py:438} INFO - [0m22:42:26  Encountered an error:
[2025-07-01T22:42:26.544+0000] {docker.py:438} INFO - Runtime Error
[2025-07-01T22:42:26.545+0000] {docker.py:438} INFO -   at path []: Additional properties are not allowed ('analysis', 'concurrent_batches', 'docs', 'thread_count' were unexpected)
[2025-07-01T22:42:26.545+0000] {docker.py:438} INFO - 
[2025-07-01T22:42:26.545+0000] {docker.py:438} INFO - Error encountered in /dbt/dbt_project.yml
[2025-07-01T22:42:27.746+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-01T22:42:27.758+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 2}
[2025-07-01T22:42:27.764+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_trino_silver_pipeline, task_id=dbt_run_silver, run_id=scheduled__2025-07-01T22:40:00+00:00, execution_date=20250701T224000, start_date=20250701T224216, end_date=20250701T224227
[2025-07-01T22:42:27.789+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 47 for task dbt_run_silver (Docker container failed: {'StatusCode': 2}; 186)
[2025-07-01T22:42:27.834+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-01T22:42:27.874+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T22:42:27.881+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
