[2025-07-01T22:28:00.949+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-01T22:28:00.998+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:26:00+00:00 [queued]>
[2025-07-01T22:28:01.008+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:26:00+00:00 [queued]>
[2025-07-01T22:28:01.008+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-01T22:28:01.020+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): dbt_run_silver> on 2025-07-01 22:26:00+00:00
[2025-07-01T22:28:01.029+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1096) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-01T22:28:01.028+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_trino_silver_pipeline', 'dbt_run_silver', 'scheduled__2025-07-01T22:26:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dbt_trino_silver_dag.py', '--cfg-path', '/tmp/tmpb61z74fc']
[2025-07-01T22:28:01.030+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask dbt_run_silver
[2025-07-01T22:28:01.030+0000] {standard_task_runner.py:64} INFO - Started process 1097 to run task
[2025-07-01T22:28:01.076+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:26:00+00:00 [running]> on host 891f6be6864d
[2025-07-01T22:28:01.161+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@example.com' AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='dbt_trino_silver_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T22:26:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T22:26:00+00:00'
[2025-07-01T22:28:01.162+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-01T22:28:01.221+0000] {docker.py:367} INFO - Starting docker container from image modern-data-pipeline-dbt-trino:latest
[2025-07-01T22:28:01.601+0000] {docker.py:438} INFO - === Executando dbt run incremental ===
[2025-07-01T22:28:05.713+0000] {docker.py:438} INFO - [0m22:28:05  Running with dbt=1.7.0
[2025-07-01T22:28:06.187+0000] {docker.py:438} INFO - [0m22:28:06  Registered adapter: trino=1.7.0
[2025-07-01T22:28:06.263+0000] {docker.py:438} INFO - [0m22:28:06  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-07-01T22:28:06.263+0000] {docker.py:438} INFO - There are 1 unused configuration paths:
[2025-07-01T22:28:06.263+0000] {docker.py:438} INFO - - models.agronegocio_iceberg.staging
[2025-07-01T22:28:06.292+0000] {docker.py:438} INFO - [0m22:28:06  Found 1 model, 29 tests, 2 operations, 1 source, 0 exposures, 0 metrics, 541 macros, 0 groups, 0 semantic models
[2025-07-01T22:28:06.295+0000] {docker.py:438} INFO - [0m22:28:06
[2025-07-01T22:28:06.628+0000] {docker.py:438} INFO - [0m22:28:06
[2025-07-01T22:28:06.629+0000] {docker.py:438} INFO - [0m22:28:06  Running 1 on-run-start hook
[2025-07-01T22:28:06.635+0000] {docker.py:438} INFO - [0m22:28:06  Iniciando execu√ß√£o do dbt com Trino/Iceberg
[2025-07-01T22:28:06.640+0000] {docker.py:438} INFO - [0m22:28:06  1 of 1 START hook: agronegocio_iceberg.on-run-start.0 .......................... [RUN]
[2025-07-01T22:28:06.641+0000] {docker.py:438} INFO - [0m22:28:06  1 of 1 OK hook: agronegocio_iceberg.on-run-start.0 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T22:28:06.642+0000] {docker.py:438} INFO - [0m22:28:06
[2025-07-01T22:28:06.643+0000] {docker.py:438} INFO - [0m22:28:06  Concurrency: 2 threads (target='dev')
[2025-07-01T22:28:06.644+0000] {docker.py:438} INFO - [0m22:28:06
[2025-07-01T22:28:06.654+0000] {docker.py:438} INFO - [0m22:28:06  1 of 1 START sql incremental model silver_silver.silver_dados_produtores_agro_trino  [RUN]
[2025-07-01T22:28:06.834+0000] {docker.py:438} INFO - [0m22:28:06  Schema silver criado/verificado
[2025-07-01T22:28:06.932+0000] {docker.py:438} INFO - [0m22:28:06  1 of 1 ERROR creating sql incremental model silver_silver.silver_dados_produtores_agro_trino  [[31mERROR[0m in 0.28s]
[2025-07-01T22:28:06.935+0000] {docker.py:438} INFO - [0m22:28:06
[2025-07-01T22:28:06.936+0000] {docker.py:438} INFO - [0m22:28:06  Running 1 on-run-end hook
[2025-07-01T22:28:06.944+0000] {docker.py:438} INFO - [0m22:28:06  Execu√ß√£o finalizada
[2025-07-01T22:28:06.948+0000] {docker.py:438} INFO - [0m22:28:06  1 of 1 START hook: agronegocio_iceberg.on-run-end.0 ............................ [RUN]
[2025-07-01T22:28:06.949+0000] {docker.py:438} INFO - [0m22:28:06  1 of 1 OK hook: agronegocio_iceberg.on-run-end.0 ............................... [[32mOK[0m in 0.00s]
[2025-07-01T22:28:06.950+0000] {docker.py:438} INFO - [0m22:28:06
[2025-07-01T22:28:06.952+0000] {docker.py:438} INFO - [0m22:28:06  
[2025-07-01T22:28:06.952+0000] {docker.py:438} INFO - [0m22:28:06  Finished running 1 incremental model, 2 hooks in 0 hours 0 minutes and 0.65 seconds (0.65s).
[2025-07-01T22:28:06.968+0000] {docker.py:438} INFO - [0m22:28:06
[2025-07-01T22:28:06.969+0000] {docker.py:438} INFO - [0m22:28:06  [31mCompleted with 1 error and 0 warnings:[0m
[2025-07-01T22:28:06.970+0000] {docker.py:438} INFO - [0m22:28:06
[2025-07-01T22:28:06.971+0000] {docker.py:438} INFO - [0m22:28:06    Database Error in model silver_dados_produtores_agro_trino (models/silver/silver_dados_produtores_agro_trino.sql)
[2025-07-01T22:28:06.971+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 104:18: Column 'serasa_score' cannot be resolved", query_id=20250701_222806_00084_tzkb6)
[2025-07-01T22:28:06.971+0000] {docker.py:438} INFO -   compiled Code at target/run/agronegocio_iceberg/models/silver/silver_dados_produtores_agro_trino.sql
[2025-07-01T22:28:06.972+0000] {docker.py:438} INFO - [0m22:28:06
[2025-07-01T22:28:06.972+0000] {docker.py:438} INFO - [0m22:28:06  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-07-01T22:28:08.190+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-01T22:28:08.200+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-01T22:28:08.205+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_trino_silver_pipeline, task_id=dbt_run_silver, run_id=scheduled__2025-07-01T22:26:00+00:00, execution_date=20250701T222600, start_date=20250701T222800, end_date=20250701T222808
[2025-07-01T22:28:08.219+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 36 for task dbt_run_silver (Docker container failed: {'StatusCode': 1}; 1097)
[2025-07-01T22:28:08.246+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-01T22:28:08.275+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T22:28:08.281+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
