[2025-07-01T22:06:01.975+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-01T22:06:02.029+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:04:00+00:00 [queued]>
[2025-07-01T22:06:02.044+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:04:00+00:00 [queued]>
[2025-07-01T22:06:02.044+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-01T22:06:02.068+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): dbt_run_silver> on 2025-07-01 22:04:00+00:00
[2025-07-01T22:06:02.080+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=667) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-01T22:06:02.081+0000] {standard_task_runner.py:64} INFO - Started process 668 to run task
[2025-07-01T22:06:02.088+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_trino_silver_pipeline', 'dbt_run_silver', 'scheduled__2025-07-01T22:04:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dbt_trino_silver_dag.py', '--cfg-path', '/tmp/tmpv0b29bhu']
[2025-07-01T22:06:02.090+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask dbt_run_silver
[2025-07-01T22:06:02.174+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:04:00+00:00 [running]> on host 891f6be6864d
[2025-07-01T22:06:02.382+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@example.com' AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='dbt_trino_silver_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T22:04:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T22:04:00+00:00'
[2025-07-01T22:06:02.383+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-01T22:06:02.468+0000] {docker.py:367} INFO - Starting docker container from image modern-data-pipeline-dbt-trino:latest
[2025-07-01T22:06:03.066+0000] {docker.py:438} INFO - === Executando dbt run incremental ===
[2025-07-01T22:06:06.481+0000] {docker.py:438} INFO - [0m22:06:06  Running with dbt=1.7.0
[2025-07-01T22:06:06.962+0000] {docker.py:438} INFO - [0m22:06:06  Registered adapter: trino=1.7.0
[2025-07-01T22:06:07.030+0000] {docker.py:438} INFO - [0m22:06:07  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-07-01T22:06:07.031+0000] {docker.py:438} INFO - There are 1 unused configuration paths:
[2025-07-01T22:06:07.031+0000] {docker.py:438} INFO - - models.agronegocio_iceberg.staging
[2025-07-01T22:06:07.061+0000] {docker.py:438} INFO - [0m22:06:07  Found 1 model, 29 tests, 2 operations, 1 source, 0 exposures, 0 metrics, 541 macros, 0 groups, 0 semantic models
[2025-07-01T22:06:07.064+0000] {docker.py:438} INFO - [0m22:06:07
[2025-07-01T22:06:07.495+0000] {docker.py:438} INFO - [0m22:06:07
[2025-07-01T22:06:07.496+0000] {docker.py:438} INFO - [0m22:06:07  Running 1 on-run-start hook
[2025-07-01T22:06:07.502+0000] {docker.py:438} INFO - [0m22:06:07  Iniciando execu√ß√£o do dbt com Trino/Iceberg
[2025-07-01T22:06:07.507+0000] {docker.py:438} INFO - [0m22:06:07  1 of 1 START hook: agronegocio_iceberg.on-run-start.0 .......................... [RUN]
[2025-07-01T22:06:07.508+0000] {docker.py:438} INFO - [0m22:06:07  1 of 1 OK hook: agronegocio_iceberg.on-run-start.0 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T22:06:07.509+0000] {docker.py:438} INFO - [0m22:06:07
[2025-07-01T22:06:07.510+0000] {docker.py:438} INFO - [0m22:06:07  Concurrency: 2 threads (target='dev')
[2025-07-01T22:06:07.511+0000] {docker.py:438} INFO - [0m22:06:07
[2025-07-01T22:06:07.524+0000] {docker.py:438} INFO - [0m22:06:07  1 of 1 START sql incremental model silver_silver.silver_dados_produtores_agro_trino  [RUN]
[2025-07-01T22:06:07.698+0000] {docker.py:438} INFO - [0m22:06:07  Schema silver criado/verificado
[2025-07-01T22:06:07.820+0000] {docker.py:438} INFO - [0m22:06:07  1 of 1 ERROR creating sql incremental model silver_silver.silver_dados_produtores_agro_trino  [[31mERROR[0m in 0.29s]
[2025-07-01T22:06:07.823+0000] {docker.py:438} INFO - [0m22:06:07
[2025-07-01T22:06:07.824+0000] {docker.py:438} INFO - [0m22:06:07  Running 1 on-run-end hook
[2025-07-01T22:06:07.830+0000] {docker.py:438} INFO - [0m22:06:07  Execu√ß√£o finalizada
[2025-07-01T22:06:07.832+0000] {docker.py:438} INFO - [0m22:06:07  1 of 1 START hook: agronegocio_iceberg.on-run-end.0 ............................ [RUN]
[2025-07-01T22:06:07.833+0000] {docker.py:438} INFO - [0m22:06:07  1 of 1 OK hook: agronegocio_iceberg.on-run-end.0 ............................... [[32mOK[0m in 0.00s]
[2025-07-01T22:06:07.833+0000] {docker.py:438} INFO - [0m22:06:07
[2025-07-01T22:06:07.836+0000] {docker.py:438} INFO - [0m22:06:07
[2025-07-01T22:06:07.837+0000] {docker.py:438} INFO - [0m22:06:07  Finished running 1 incremental model, 2 hooks in 0 hours 0 minutes and 0.77 seconds (0.77s).
[2025-07-01T22:06:07.851+0000] {docker.py:438} INFO - [0m22:06:07
[2025-07-01T22:06:07.852+0000] {docker.py:438} INFO - [0m22:06:07  [31mCompleted with 1 error and 0 warnings:[0m
[2025-07-01T22:06:07.853+0000] {docker.py:438} INFO - [0m22:06:07
[2025-07-01T22:06:07.854+0000] {docker.py:438} INFO - [0m22:06:07    Database Error in model silver_dados_produtores_agro_trino (models/silver/silver_dados_produtores_agro_trino.sql)
[2025-07-01T22:06:07.854+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 104:18: Column 'serasa_score' cannot be resolved", query_id=20250701_220607_00029_tzkb6)
[2025-07-01T22:06:07.854+0000] {docker.py:438} INFO -   compiled Code at target/run/agronegocio_iceberg/models/silver/silver_dados_produtores_agro_trino.sql
[2025-07-01T22:06:07.854+0000] {docker.py:438} INFO - [0m22:06:07
[2025-07-01T22:06:07.855+0000] {docker.py:438} INFO - [0m22:06:07  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-07-01T22:06:09.208+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-01T22:06:09.215+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-01T22:06:09.220+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_trino_silver_pipeline, task_id=dbt_run_silver, run_id=scheduled__2025-07-01T22:04:00+00:00, execution_date=20250701T220400, start_date=20250701T220602, end_date=20250701T220609
[2025-07-01T22:06:09.233+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task dbt_run_silver (Docker container failed: {'StatusCode': 1}; 668)
[2025-07-01T22:06:09.277+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-01T22:06:09.299+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T22:06:09.303+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
