[2025-07-01T22:18:01.670+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-01T22:18:01.719+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:16:00+00:00 [queued]>
[2025-07-01T22:18:01.735+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:16:00+00:00 [queued]>
[2025-07-01T22:18:01.735+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-01T22:18:01.763+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): dbt_run_silver> on 2025-07-01 22:16:00+00:00
[2025-07-01T22:18:01.773+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=895) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-01T22:18:01.775+0000] {standard_task_runner.py:64} INFO - Started process 896 to run task
[2025-07-01T22:18:01.780+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_trino_silver_pipeline', 'dbt_run_silver', 'scheduled__2025-07-01T22:16:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dbt_trino_silver_dag.py', '--cfg-path', '/tmp/tmp1bh5khg3']
[2025-07-01T22:18:01.783+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask dbt_run_silver
[2025-07-01T22:18:01.854+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:16:00+00:00 [running]> on host 891f6be6864d
[2025-07-01T22:18:01.979+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@example.com' AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='dbt_trino_silver_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T22:16:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T22:16:00+00:00'
[2025-07-01T22:18:01.980+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-01T22:18:02.033+0000] {docker.py:367} INFO - Starting docker container from image modern-data-pipeline-dbt-trino:latest
[2025-07-01T22:18:02.431+0000] {docker.py:438} INFO - === Executando dbt run incremental ===
[2025-07-01T22:18:05.841+0000] {docker.py:438} INFO - [0m22:18:05  Running with dbt=1.7.0
[2025-07-01T22:18:06.314+0000] {docker.py:438} INFO - [0m22:18:06  Registered adapter: trino=1.7.0
[2025-07-01T22:18:06.393+0000] {docker.py:438} INFO - [0m22:18:06  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-07-01T22:18:06.393+0000] {docker.py:438} INFO - There are 1 unused configuration paths:
[2025-07-01T22:18:06.393+0000] {docker.py:438} INFO - - models.agronegocio_iceberg.staging
[2025-07-01T22:18:06.426+0000] {docker.py:438} INFO - [0m22:18:06  Found 1 model, 29 tests, 2 operations, 1 source, 0 exposures, 0 metrics, 541 macros, 0 groups, 0 semantic models
[2025-07-01T22:18:06.431+0000] {docker.py:438} INFO - [0m22:18:06
[2025-07-01T22:18:06.881+0000] {docker.py:438} INFO - [0m22:18:06
[2025-07-01T22:18:06.883+0000] {docker.py:438} INFO - [0m22:18:06  Running 1 on-run-start hook
[2025-07-01T22:18:06.892+0000] {docker.py:438} INFO - [0m22:18:06  Iniciando execu√ß√£o do dbt com Trino/Iceberg
[2025-07-01T22:18:06.902+0000] {docker.py:438} INFO - [0m22:18:06  1 of 1 START hook: agronegocio_iceberg.on-run-start.0 .......................... [RUN]
[2025-07-01T22:18:06.903+0000] {docker.py:438} INFO - [0m22:18:06  1 of 1 OK hook: agronegocio_iceberg.on-run-start.0 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T22:18:06.907+0000] {docker.py:438} INFO - [0m22:18:06  
[2025-07-01T22:18:06.907+0000] {docker.py:438} INFO - [0m22:18:06  Concurrency: 2 threads (target='dev')
[2025-07-01T22:18:06.907+0000] {docker.py:438} INFO - [0m22:18:06
[2025-07-01T22:18:06.923+0000] {docker.py:438} INFO - [0m22:18:06  1 of 1 START sql incremental model silver_silver.silver_dados_produtores_agro_trino  [RUN]
[2025-07-01T22:18:07.111+0000] {docker.py:438} INFO - [0m22:18:07  Schema silver criado/verificado
[2025-07-01T22:18:07.212+0000] {docker.py:438} INFO - [0m22:18:07  1 of 1 ERROR creating sql incremental model silver_silver.silver_dados_produtores_agro_trino  [[31mERROR[0m in 0.29s]
[2025-07-01T22:18:07.215+0000] {docker.py:438} INFO - [0m22:18:07
[2025-07-01T22:18:07.216+0000] {docker.py:438} INFO - [0m22:18:07  Running 1 on-run-end hook
[2025-07-01T22:18:07.221+0000] {docker.py:438} INFO - [0m22:18:07  Execu√ß√£o finalizada
[2025-07-01T22:18:07.222+0000] {docker.py:438} INFO - [0m22:18:07  1 of 1 START hook: agronegocio_iceberg.on-run-end.0 ............................ [RUN]
[2025-07-01T22:18:07.223+0000] {docker.py:438} INFO - [0m22:18:07  1 of 1 OK hook: agronegocio_iceberg.on-run-end.0 ............................... [[32mOK[0m in 0.00s]
[2025-07-01T22:18:07.224+0000] {docker.py:438} INFO - [0m22:18:07
[2025-07-01T22:18:07.228+0000] {docker.py:438} INFO - [0m22:18:07
[2025-07-01T22:18:07.229+0000] {docker.py:438} INFO - [0m22:18:07  Finished running 1 incremental model, 2 hooks in 0 hours 0 minutes and 0.80 seconds (0.80s).
[2025-07-01T22:18:07.246+0000] {docker.py:438} INFO - [0m22:18:07
[2025-07-01T22:18:07.246+0000] {docker.py:438} INFO - [0m22:18:07  [31mCompleted with 1 error and 0 warnings:[0m
[2025-07-01T22:18:07.247+0000] {docker.py:438} INFO - [0m22:18:07
[2025-07-01T22:18:07.248+0000] {docker.py:438} INFO - [0m22:18:07    Database Error in model silver_dados_produtores_agro_trino (models/silver/silver_dados_produtores_agro_trino.sql)
[2025-07-01T22:18:07.248+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 104:18: Column 'serasa_score' cannot be resolved", query_id=20250701_221807_00059_tzkb6)
[2025-07-01T22:18:07.248+0000] {docker.py:438} INFO -   compiled Code at target/run/agronegocio_iceberg/models/silver/silver_dados_produtores_agro_trino.sql
[2025-07-01T22:18:07.249+0000] {docker.py:438} INFO - [0m22:18:07
[2025-07-01T22:18:07.249+0000] {docker.py:438} INFO - [0m22:18:07  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-07-01T22:18:08.610+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-01T22:18:08.622+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-01T22:18:08.630+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_trino_silver_pipeline, task_id=dbt_run_silver, run_id=scheduled__2025-07-01T22:16:00+00:00, execution_date=20250701T221600, start_date=20250701T221801, end_date=20250701T221808
[2025-07-01T22:18:08.650+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 26 for task dbt_run_silver (Docker container failed: {'StatusCode': 1}; 896)
[2025-07-01T22:18:08.690+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-01T22:18:08.724+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T22:18:08.730+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
