[2025-07-01T22:02:02.056+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-01T22:02:02.100+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T21:58:00+00:00 [queued]>
[2025-07-01T22:02:02.116+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T21:58:00+00:00 [queued]>
[2025-07-01T22:02:02.116+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-07-01T22:02:02.135+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): dbt_run_silver> on 2025-07-01 21:58:00+00:00
[2025-07-01T22:02:02.145+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_trino_silver_pipeline', 'dbt_run_silver', 'scheduled__2025-07-01T21:58:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dbt_trino_silver_dag.py', '--cfg-path', '/tmp/tmpkp16kfbc']
[2025-07-01T22:02:02.147+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask dbt_run_silver
[2025-07-01T22:02:02.147+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=583) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-01T22:02:02.149+0000] {standard_task_runner.py:64} INFO - Started process 584 to run task
[2025-07-01T22:02:02.211+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T21:58:00+00:00 [running]> on host 891f6be6864d
[2025-07-01T22:02:02.322+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@example.com' AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='dbt_trino_silver_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T21:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T21:58:00+00:00'
[2025-07-01T22:02:02.324+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-01T22:02:02.363+0000] {docker.py:367} INFO - Starting docker container from image modern-data-pipeline-dbt-trino:latest
[2025-07-01T22:02:02.684+0000] {docker.py:438} INFO - === Executando dbt run incremental ===
[2025-07-01T22:02:06.639+0000] {docker.py:438} INFO - [0m22:02:06  Running with dbt=1.7.0
[2025-07-01T22:02:07.358+0000] {docker.py:438} INFO - [0m22:02:07  Registered adapter: trino=1.7.0
[2025-07-01T22:02:07.473+0000] {docker.py:438} INFO - [0m22:02:07  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-07-01T22:02:07.473+0000] {docker.py:438} INFO - There are 1 unused configuration paths:
[2025-07-01T22:02:07.473+0000] {docker.py:438} INFO - - models.agronegocio_iceberg.staging
[2025-07-01T22:02:07.520+0000] {docker.py:438} INFO - [0m22:02:07  Found 1 model, 29 tests, 2 operations, 1 source, 0 exposures, 0 metrics, 541 macros, 0 groups, 0 semantic models
[2025-07-01T22:02:07.527+0000] {docker.py:438} INFO - [0m22:02:07
[2025-07-01T22:02:08.298+0000] {docker.py:438} INFO - [0m22:02:08
[2025-07-01T22:02:08.304+0000] {docker.py:438} INFO - [0m22:02:08  Running 1 on-run-start hook
[2025-07-01T22:02:08.320+0000] {docker.py:438} INFO - [0m22:02:08  Iniciando execu√ß√£o do dbt com Trino/Iceberg
[2025-07-01T22:02:08.332+0000] {docker.py:438} INFO - [0m22:02:08  1 of 1 START hook: agronegocio_iceberg.on-run-start.0 .......................... [RUN]
[2025-07-01T22:02:08.334+0000] {docker.py:438} INFO - [0m22:02:08  1 of 1 OK hook: agronegocio_iceberg.on-run-start.0 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T22:02:08.337+0000] {docker.py:438} INFO - [0m22:02:08
[2025-07-01T22:02:08.341+0000] {docker.py:438} INFO - [0m22:02:08  Concurrency: 2 threads (target='dev')
[2025-07-01T22:02:08.342+0000] {docker.py:438} INFO - [0m22:02:08
[2025-07-01T22:02:08.361+0000] {docker.py:438} INFO - [0m22:02:08  1 of 1 START sql incremental model silver_silver.silver_dados_produtores_agro_trino  [RUN]
[2025-07-01T22:02:08.563+0000] {docker.py:438} INFO - [0m22:02:08  Schema silver criado/verificado
[2025-07-01T22:02:08.741+0000] {docker.py:438} INFO - [0m22:02:08  1 of 1 ERROR creating sql incremental model silver_silver.silver_dados_produtores_agro_trino  [[31mERROR[0m in 0.38s]
[2025-07-01T22:02:08.747+0000] {docker.py:438} INFO - [0m22:02:08
[2025-07-01T22:02:08.749+0000] {docker.py:438} INFO - [0m22:02:08  Running 1 on-run-end hook
[2025-07-01T22:02:08.756+0000] {docker.py:438} INFO - [0m22:02:08  Execu√ß√£o finalizada
[2025-07-01T22:02:08.758+0000] {docker.py:438} INFO - [0m22:02:08  1 of 1 START hook: agronegocio_iceberg.on-run-end.0 ............................ [RUN]
[2025-07-01T22:02:08.760+0000] {docker.py:438} INFO - [0m22:02:08  1 of 1 OK hook: agronegocio_iceberg.on-run-end.0 ............................... [[32mOK[0m in 0.00s]
[2025-07-01T22:02:08.760+0000] {docker.py:438} INFO - [0m22:02:08
[2025-07-01T22:02:08.763+0000] {docker.py:438} INFO - [0m22:02:08
[2025-07-01T22:02:08.764+0000] {docker.py:438} INFO - [0m22:02:08  Finished running 1 incremental model, 2 hooks in 0 hours 0 minutes and 1.24 seconds (1.24s).
[2025-07-01T22:02:08.783+0000] {docker.py:438} INFO - [0m22:02:08
[2025-07-01T22:02:08.784+0000] {docker.py:438} INFO - [0m22:02:08  [31mCompleted with 1 error and 0 warnings:[0m
[2025-07-01T22:02:08.785+0000] {docker.py:438} INFO - [0m22:02:08
[2025-07-01T22:02:08.786+0000] {docker.py:438} INFO - [0m22:02:08    Database Error in model silver_dados_produtores_agro_trino (models/silver/silver_dados_produtores_agro_trino.sql)
[2025-07-01T22:02:08.786+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 104:18: Column 'serasa_score' cannot be resolved", query_id=20250701_220208_00014_tzkb6)
[2025-07-01T22:02:08.787+0000] {docker.py:438} INFO -   compiled Code at target/run/agronegocio_iceberg/models/silver/silver_dados_produtores_agro_trino.sql
[2025-07-01T22:02:08.787+0000] {docker.py:438} INFO - [0m22:02:08
[2025-07-01T22:02:08.787+0000] {docker.py:438} INFO - [0m22:02:08  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-07-01T22:02:10.209+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-01T22:02:10.217+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-01T22:02:10.221+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_trino_silver_pipeline, task_id=dbt_run_silver, run_id=scheduled__2025-07-01T21:58:00+00:00, execution_date=20250701T215800, start_date=20250701T220202, end_date=20250701T220210
[2025-07-01T22:02:10.232+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task dbt_run_silver (Docker container failed: {'StatusCode': 1}; 584)
[2025-07-01T22:02:10.265+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-01T22:02:10.284+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T22:02:10.287+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
