[2025-07-01T22:00:37.569+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-01T22:00:37.601+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T21:58:00+00:00 [queued]>
[2025-07-01T22:00:37.611+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T21:58:00+00:00 [queued]>
[2025-07-01T22:00:37.611+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-01T22:00:37.626+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): dbt_run_silver> on 2025-07-01 21:58:00+00:00
[2025-07-01T22:00:37.634+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=554) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-01T22:00:37.635+0000] {standard_task_runner.py:64} INFO - Started process 555 to run task
[2025-07-01T22:00:37.634+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_trino_silver_pipeline', 'dbt_run_silver', 'scheduled__2025-07-01T21:58:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dbt_trino_silver_dag.py', '--cfg-path', '/tmp/tmplbhmasfe']
[2025-07-01T22:00:37.637+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask dbt_run_silver
[2025-07-01T22:00:37.681+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T21:58:00+00:00 [running]> on host 891f6be6864d
[2025-07-01T22:00:37.779+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@example.com' AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='dbt_trino_silver_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T21:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T21:58:00+00:00'
[2025-07-01T22:00:37.780+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-01T22:00:37.821+0000] {docker.py:367} INFO - Starting docker container from image modern-data-pipeline-dbt-trino:latest
[2025-07-01T22:00:38.137+0000] {docker.py:438} INFO - === Executando dbt run incremental ===
[2025-07-01T22:00:42.390+0000] {docker.py:438} INFO - [0m22:00:42  Running with dbt=1.7.0
[2025-07-01T22:00:43.251+0000] {docker.py:438} INFO - [0m22:00:43  Registered adapter: trino=1.7.0
[2025-07-01T22:00:43.325+0000] {docker.py:438} INFO - [0m22:00:43  Unable to do partial parsing because profile has changed
[2025-07-01T22:00:47.010+0000] {docker.py:438} INFO - [0m22:00:47  Iniciando execu√ß√£o do dbt com Trino/Iceberg
[2025-07-01T22:00:47.028+0000] {docker.py:438} INFO - [0m22:00:47  Execu√ß√£o finalizada
[2025-07-01T22:00:48.059+0000] {docker.py:438} INFO - [0m22:00:48  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-07-01T22:00:48.059+0000] {docker.py:438} INFO - There are 1 unused configuration paths:
[2025-07-01T22:00:48.060+0000] {docker.py:438} INFO - - models.agronegocio_iceberg.staging
[2025-07-01T22:00:48.103+0000] {docker.py:438} INFO - [0m22:00:48  Found 1 model, 29 tests, 2 operations, 1 source, 0 exposures, 0 metrics, 541 macros, 0 groups, 0 semantic models
[2025-07-01T22:00:48.107+0000] {docker.py:438} INFO - [0m22:00:48
[2025-07-01T22:00:53.898+0000] {docker.py:438} INFO - [0m22:00:53
[2025-07-01T22:00:53.922+0000] {docker.py:438} INFO - [0m22:00:53  Running 1 on-run-start hook
[2025-07-01T22:00:53.944+0000] {docker.py:438} INFO - [0m22:00:53  Iniciando execu√ß√£o do dbt com Trino/Iceberg
[2025-07-01T22:00:53.972+0000] {docker.py:438} INFO - [0m22:00:53  1 of 1 START hook: agronegocio_iceberg.on-run-start.0 .......................... [RUN]
[2025-07-01T22:00:53.974+0000] {docker.py:438} INFO - [0m22:00:53  1 of 1 OK hook: agronegocio_iceberg.on-run-start.0 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T22:00:53.976+0000] {docker.py:438} INFO - [0m22:00:53
[2025-07-01T22:00:53.978+0000] {docker.py:438} INFO - [0m22:00:53  Concurrency: 2 threads (target='dev')
[2025-07-01T22:00:53.980+0000] {docker.py:438} INFO - [0m22:00:53
[2025-07-01T22:00:54.029+0000] {docker.py:438} INFO - [0m22:00:54  1 of 1 START sql incremental model silver_silver.silver_dados_produtores_agro_trino  [RUN]
[2025-07-01T22:00:54.701+0000] {docker.py:438} INFO - [0m22:00:54  Schema silver criado/verificado
[2025-07-01T22:00:59.019+0000] {docker.py:438} INFO - [0m22:00:59  1 of 1 ERROR creating sql incremental model silver_silver.silver_dados_produtores_agro_trino  [[31mERROR[0m in 4.98s]
[2025-07-01T22:00:59.023+0000] {docker.py:438} INFO - [0m22:00:59
[2025-07-01T22:00:59.024+0000] {docker.py:438} INFO - [0m22:00:59  Running 1 on-run-end hook
[2025-07-01T22:00:59.031+0000] {docker.py:438} INFO - [0m22:00:59  Execu√ß√£o finalizada
[2025-07-01T22:00:59.033+0000] {docker.py:438} INFO - [0m22:00:59  1 of 1 START hook: agronegocio_iceberg.on-run-end.0 ............................ [RUN]
[2025-07-01T22:00:59.034+0000] {docker.py:438} INFO - [0m22:00:59  1 of 1 OK hook: agronegocio_iceberg.on-run-end.0 ............................... [[32mOK[0m in 0.00s]
[2025-07-01T22:00:59.035+0000] {docker.py:438} INFO - [0m22:00:59
[2025-07-01T22:00:59.038+0000] {docker.py:438} INFO - [0m22:00:59
[2025-07-01T22:00:59.039+0000] {docker.py:438} INFO - [0m22:00:59  Finished running 1 incremental model, 2 hooks in 0 hours 0 minutes and 10.93 seconds (10.93s).
[2025-07-01T22:00:59.057+0000] {docker.py:438} INFO - [0m22:00:59
[2025-07-01T22:00:59.059+0000] {docker.py:438} INFO - [0m22:00:59  [31mCompleted with 1 error and 0 warnings:[0m
[2025-07-01T22:00:59.059+0000] {docker.py:438} INFO - [0m22:00:59
[2025-07-01T22:00:59.060+0000] {docker.py:438} INFO - [0m22:00:59    Database Error in model silver_dados_produtores_agro_trino (models/silver/silver_dados_produtores_agro_trino.sql)
[2025-07-01T22:00:59.060+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 104:18: Column 'serasa_score' cannot be resolved", query_id=20250701_220054_00009_tzkb6)
[2025-07-01T22:00:59.061+0000] {docker.py:438} INFO -   compiled Code at target/run/agronegocio_iceberg/models/silver/silver_dados_produtores_agro_trino.sql
[2025-07-01T22:00:59.061+0000] {docker.py:438} INFO - [0m22:00:59
[2025-07-01T22:00:59.062+0000] {docker.py:438} INFO - [0m22:00:59  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-07-01T22:01:00.925+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-01T22:01:00.939+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-01T22:01:00.947+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_trino_silver_pipeline, task_id=dbt_run_silver, run_id=scheduled__2025-07-01T21:58:00+00:00, execution_date=20250701T215800, start_date=20250701T220037, end_date=20250701T220100
[2025-07-01T22:01:00.971+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task dbt_run_silver (Docker container failed: {'StatusCode': 1}; 555)
[2025-07-01T22:01:00.988+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-01T22:01:01.020+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T22:01:01.025+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
