[2025-07-01T21:59:19.473+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-01T21:59:19.507+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T21:54:00+00:00 [queued]>
[2025-07-01T21:59:19.518+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T21:54:00+00:00 [queued]>
[2025-07-01T21:59:19.518+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-07-01T21:59:19.531+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): dbt_run_silver> on 2025-07-01 21:54:00+00:00
[2025-07-01T21:59:19.537+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=522) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-01T21:59:19.538+0000] {standard_task_runner.py:64} INFO - Started process 523 to run task
[2025-07-01T21:59:19.537+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_trino_silver_pipeline', 'dbt_run_silver', 'scheduled__2025-07-01T21:54:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dbt_trino_silver_dag.py', '--cfg-path', '/tmp/tmp17muyznt']
[2025-07-01T21:59:19.539+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask dbt_run_silver
[2025-07-01T21:59:19.602+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T21:54:00+00:00 [running]> on host 891f6be6864d
[2025-07-01T21:59:19.676+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@example.com' AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='dbt_trino_silver_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T21:54:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T21:54:00+00:00'
[2025-07-01T21:59:19.677+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-01T21:59:19.715+0000] {docker.py:367} INFO - Starting docker container from image modern-data-pipeline-dbt-trino:latest
[2025-07-01T21:59:20.035+0000] {docker.py:438} INFO - === Executando dbt run incremental ===
[2025-07-01T21:59:23.367+0000] {docker.py:438} INFO - [0m21:59:23  Running with dbt=1.7.0
[2025-07-01T21:59:23.836+0000] {docker.py:438} INFO - [0m21:59:23  Registered adapter: trino=1.7.0
[2025-07-01T21:59:23.915+0000] {docker.py:438} INFO - [0m21:59:23  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-07-01T21:59:23.916+0000] {docker.py:438} INFO - There are 1 unused configuration paths:
[2025-07-01T21:59:23.916+0000] {docker.py:438} INFO - - models.agronegocio_iceberg.staging
[2025-07-01T21:59:23.954+0000] {docker.py:438} INFO - [0m21:59:23  Found 1 model, 29 tests, 2 operations, 1 source, 0 exposures, 0 metrics, 541 macros, 0 groups, 0 semantic models
[2025-07-01T21:59:23.957+0000] {docker.py:438} INFO - [0m21:59:23
[2025-07-01T21:59:24.007+0000] {docker.py:438} INFO - [0m21:59:24
[2025-07-01T21:59:24.007+0000] {docker.py:438} INFO - [0m21:59:24  Finished running  in 0 hours 0 minutes and 0.05 seconds (0.05s).
[2025-07-01T21:59:24.008+0000] {docker.py:438} INFO - [0m21:59:24  Encountered an error:
[2025-07-01T21:59:24.009+0000] {docker.py:438} INFO - Database Error
[2025-07-01T21:59:24.009+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=INVALID_SESSION_PROPERTY, message="Unknown session property exchange_compression", query_id=20250701_215923_00002_tzkb6)
[2025-07-01T21:59:25.282+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-01T21:59:25.290+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 2}
[2025-07-01T21:59:25.295+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_trino_silver_pipeline, task_id=dbt_run_silver, run_id=scheduled__2025-07-01T21:54:00+00:00, execution_date=20250701T215400, start_date=20250701T215919, end_date=20250701T215925
[2025-07-01T21:59:25.307+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task dbt_run_silver (Docker container failed: {'StatusCode': 2}; 523)
[2025-07-01T21:59:25.325+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-01T21:59:25.350+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T21:59:25.352+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
