[2025-07-01T22:32:01.932+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-01T22:32:02.003+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:30:00+00:00 [queued]>
[2025-07-01T22:32:02.023+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:30:00+00:00 [queued]>
[2025-07-01T22:32:02.024+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-01T22:32:02.054+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): dbt_run_silver> on 2025-07-01 22:30:00+00:00
[2025-07-01T22:32:02.065+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1178) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-01T22:32:02.065+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_trino_silver_pipeline', 'dbt_run_silver', 'scheduled__2025-07-01T22:30:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/dbt_trino_silver_dag.py', '--cfg-path', '/tmp/tmp10xepjld']
[2025-07-01T22:32:02.067+0000] {standard_task_runner.py:64} INFO - Started process 1179 to run task
[2025-07-01T22:32:02.069+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask dbt_run_silver
[2025-07-01T22:32:02.149+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:30:00+00:00 [running]> on host 891f6be6864d
[2025-07-01T22:32:02.308+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@example.com' AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='dbt_trino_silver_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T22:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T22:30:00+00:00'
[2025-07-01T22:32:02.309+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-01T22:32:02.368+0000] {docker.py:367} INFO - Starting docker container from image modern-data-pipeline-dbt-trino:latest
[2025-07-01T22:32:02.995+0000] {docker.py:438} INFO - === Executando dbt run incremental ===
[2025-07-01T22:32:07.455+0000] {docker.py:438} INFO - [0m22:32:07  Running with dbt=1.7.0
[2025-07-01T22:32:08.049+0000] {docker.py:438} INFO - [0m22:32:08  Registered adapter: trino=1.7.0
[2025-07-01T22:32:08.156+0000] {docker.py:438} INFO - [0m22:32:08  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-07-01T22:32:08.156+0000] {docker.py:438} INFO - There are 1 unused configuration paths:
[2025-07-01T22:32:08.157+0000] {docker.py:438} INFO - - models.agronegocio_iceberg.staging
[2025-07-01T22:32:08.200+0000] {docker.py:438} INFO - [0m22:32:08  Found 1 model, 29 tests, 2 operations, 1 source, 0 exposures, 0 metrics, 541 macros, 0 groups, 0 semantic models
[2025-07-01T22:32:08.205+0000] {docker.py:438} INFO - [0m22:32:08
[2025-07-01T22:32:08.657+0000] {docker.py:438} INFO - [0m22:32:08
[2025-07-01T22:32:08.658+0000] {docker.py:438} INFO - [0m22:32:08  Running 1 on-run-start hook
[2025-07-01T22:32:08.666+0000] {docker.py:438} INFO - [0m22:32:08  Iniciando execu√ß√£o do dbt com Trino/Iceberg
[2025-07-01T22:32:08.676+0000] {docker.py:438} INFO - [0m22:32:08  1 of 1 START hook: agronegocio_iceberg.on-run-start.0 .......................... [RUN]
[2025-07-01T22:32:08.677+0000] {docker.py:438} INFO - [0m22:32:08  1 of 1 OK hook: agronegocio_iceberg.on-run-start.0 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T22:32:08.679+0000] {docker.py:438} INFO - [0m22:32:08
[2025-07-01T22:32:08.681+0000] {docker.py:438} INFO - [0m22:32:08  Concurrency: 2 threads (target='dev')
[2025-07-01T22:32:08.683+0000] {docker.py:438} INFO - [0m22:32:08
[2025-07-01T22:32:08.701+0000] {docker.py:438} INFO - [0m22:32:08  1 of 1 START sql incremental model silver_silver.silver_dados_produtores_agro_trino  [RUN]
[2025-07-01T22:32:08.962+0000] {docker.py:438} INFO - [0m22:32:08  Schema silver criado/verificado
[2025-07-01T22:32:09.104+0000] {docker.py:438} INFO - [0m22:32:09  1 of 1 ERROR creating sql incremental model silver_silver.silver_dados_produtores_agro_trino  [[31mERROR[0m in 0.40s]
[2025-07-01T22:32:09.109+0000] {docker.py:438} INFO - [0m22:32:09
[2025-07-01T22:32:09.111+0000] {docker.py:438} INFO - [0m22:32:09  Running 1 on-run-end hook
[2025-07-01T22:32:09.121+0000] {docker.py:438} INFO - [0m22:32:09  Execu√ß√£o finalizada
[2025-07-01T22:32:09.124+0000] {docker.py:438} INFO - [0m22:32:09  1 of 1 START hook: agronegocio_iceberg.on-run-end.0 ............................ [RUN]
[2025-07-01T22:32:09.126+0000] {docker.py:438} INFO - [0m22:32:09  1 of 1 OK hook: agronegocio_iceberg.on-run-end.0 ............................... [[32mOK[0m in 0.00s]
[2025-07-01T22:32:09.127+0000] {docker.py:438} INFO - [0m22:32:09
[2025-07-01T22:32:09.131+0000] {docker.py:438} INFO - [0m22:32:09
[2025-07-01T22:32:09.132+0000] {docker.py:438} INFO - [0m22:32:09  Finished running 1 incremental model, 2 hooks in 0 hours 0 minutes and 0.93 seconds (0.93s).
[2025-07-01T22:32:09.163+0000] {docker.py:438} INFO - [0m22:32:09
[2025-07-01T22:32:09.165+0000] {docker.py:438} INFO - [0m22:32:09  [31mCompleted with 1 error and 0 warnings:[0m
[2025-07-01T22:32:09.166+0000] {docker.py:438} INFO - [0m22:32:09
[2025-07-01T22:32:09.167+0000] {docker.py:438} INFO - [0m22:32:09    Database Error in model silver_dados_produtores_agro_trino (models/silver/silver_dados_produtores_agro_trino.sql)
[2025-07-01T22:32:09.167+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 104:18: Column 'serasa_score' cannot be resolved", query_id=20250701_223209_00094_tzkb6)
[2025-07-01T22:32:09.167+0000] {docker.py:438} INFO -   compiled Code at target/run/agronegocio_iceberg/models/silver/silver_dados_produtores_agro_trino.sql
[2025-07-01T22:32:09.168+0000] {docker.py:438} INFO - [0m22:32:09
[2025-07-01T22:32:09.170+0000] {docker.py:438} INFO - [0m22:32:09  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-07-01T22:32:10.548+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-01T22:32:10.560+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-01T22:32:10.565+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_trino_silver_pipeline, task_id=dbt_run_silver, run_id=scheduled__2025-07-01T22:30:00+00:00, execution_date=20250701T223000, start_date=20250701T223202, end_date=20250701T223210
[2025-07-01T22:32:10.596+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 40 for task dbt_run_silver (Docker container failed: {'StatusCode': 1}; 1179)
[2025-07-01T22:32:10.631+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-01T22:32:10.658+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T22:32:10.664+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
